sudo: false
language: node_js
matrix:
  include:
    - node_js: "0.12"
    - node_js: "4"
    - node_js: "io.js"
deploy:
  - provider: npm
    skip_cleanup: true
    email: "hello@dominykas.com"
    api_key:
      secure: "NyPAQlltvCIHFJ7EKSGe5ZB0BCaqQUTIx+PmeSmYc8k6DfmI8ivSJxbKpbRG1GnSme8pGTLxWnox4oo948bheGzve8m/C53vkt0gf+Au327knP746KX5R7OgCZJc5X5AhOrlT2CL9iGb2nc0GWnsi5Nj4hKjgmVanBYeY2ZKan8="
    on:
      tags: true
      node_js: "4"
